import "./globals.css";
import "raf/polyfill";
import { DefaultLayout } from "@repo/app/features/layouts";
import { Providers } from "@repo/app/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Providers>
				<body className={inter.className}>
					<DefaultLayout>{children}</DefaultLayout>
				</body>
			</Providers>
		</html>
	);
}
